#!/bin/bash
if [ ! -d "/etc/unbound" ]; then mkdir -p /etc/unbound 
fi
if [ ! -d "/etc/unbound/local.d/" ]; then mkdir -p /etc/unbound/local.d/
fi                                                                                                        

# Block advertisements, malware, and tracking domains using unbound recursive DNS
# Some lists are for personal use only

# Check if running as root
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi

# Copy adblocker.sh to adblock
#\cp -f adblock.sh /opt/adblock.sh

# IP address to send traffic
blackHoleDNS="0.0.0.0"
blackHoleDNS6="::"

# Location of configuration file
configurationFile="/etc/unbound/local.d/ad1.conf"
rm -f $configurationFile

# Clean up for refresh
rm -f /tmp/blackhole
rm -f /tmp/blackholedomains
rm -f /tmp/blackholeuniq
rm -f /tmp/blackholeconfig
touch /tmp/blackhole

# Notice for user
echo "Please wait while we gather and install blocking lists..."
curl -s https://raw.githubusercontent.com/ssolifd/1/master/hosts | grep -v "#" > /tmp/blackhole
#cat /home/share/host | grep -v "#" >> /tmp/blackhole
# Sanatize output to only domains in /tmp/blackholedomains
cat /tmp/blackhole | uniq -u > /tmp/blackholeuniq
cat /tmp/blackholeuniq | grep -v "localhost" | grep -v "local" | grep -v "127.0.0.1" | grep -v "::1" > /tmp/blackholedomains
sed -i 's/^ *//; s/ *$//; /^$/d; /^\s*$/d' /tmp/blackholedomains

# Trim and format domains for unbound 
rm -f $configurationFile
for a in `cat /tmp/blackholedomains`; do
                echo 'local-data: "'$a' A '$blackHoleDNS'"' >> /tmp/blackholeconfig
done

for a in `cat /tmp/blackholedomains`; do
                echo 'local-data: "'$a' AAAA '$blackHoleDNS6'"' >> /tmp/blackholeconfig
done

# Remove carraige return and output configuration file
tr -d '\r' < /tmp/blackholeconfig > $configurationFile


# Cleanup
rm -f /tmp/blackhole
rm -f /tmp/blackholeuniq
rm -f /tmp/blackholeconfig
systemctl restart unbound.service > /dev/null 2>&1

# Confirm completion
echo "Installed blocklist and set to update daily"
